version: "3.9"

services:
  api:
    build: ./backend
    container_name: gnss-api
    ports:
      - "8000:8000"
 
  streamlit:
    build: ./frontend
    container_name: gnss-streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api